version: '3.1'

services:
  postgres:
    container_name: sell_api
    hostname: sell_api
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
